### ISSUE TITLE
TEK002: Remove donor page and add separate cards for individual and corporate donors

### ISSUE THREAD

**Issue by bharatkashyap** [Samagra-Development/device-donation#5]
## Requirement
- Instead of two separate cards for Individual and Corporate donors showing up on clicking the Donate your smartphone card on the landing page, the idea is to have two separate cards on the landing page itself.

### Implementation

- We can remove the Donate [page](https://github.com/Samagra-Development/device-donation/blob/master/portal/pages/donate.js) and modify the landing page configuration to add the additional card with the appropriate redirect link.

- The `donatePageCards` from the [`config.js`](https://github.com/Samagra-Development/device-donation/blob/master/portal/components/config.js) can be removed and added to the `homePageCards`

- The `"Donate Your Phone"` can be removed from the `homePageCards` in the config

### Additional Considerations

- Upon adding an additional card to the landing page, the styles will have to be suitably adjusted to make sure there is no breakage for both small and large screens.

- On large screens, the viewport can be made to scroll given five cards might not fit in a single page.

**Comment by bharatkashyap** [comment]
The card text for individual and corporate donors should read: 
- "Donate a Smartphone as an Individual Donor" for individual donor
- "Donate a smartphone as a corporate donor" for corporate donor

**Comment by sagar-techjoomla** [comment]
mobile screen :

![mobile-screen-3000-2021-07-13-19_26_24](https://user-images.githubusercontent.com/87368607/125467501-ea4cbb05-9120-4b60-85b1-1ebe7a65acd4.png)

large screen :

![screen-large-3000-2021-07-13-19_26_41](https://user-images.githubusercontent.com/87368607/125467621-5ca72b61-70bb-4432-b456-380c658cf84c.png)

**Comment by sagar-techjoomla** [comment]
mobile screen:

![screen-mobile-3000-2021-07-13-19_58_33](https://user-images.githubusercontent.com/87368607/125470276-fd49e24f-1133-4732-b0c0-7ccff03c61c7.png)

large screen:

![screen-large-3000-2021-07-13-19_58_00](https://user-images.githubusercontent.com/87368607/125470345-687b8665-1e35-4774-83d6-4a62883d61fa.png)

**Comment by bharatkashyap** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Device Donation Portal](https://trello.com/c/yHmYSU0K/525-device-donation-portal)
